server:
  port: 8088
  tomcat:
    uri-encoding: UTF-8
mybatis:
  mapper-locations: classpath:mapper/*.xml
  config-location: classpath:conf/mybatis-config.xml
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      connection-timeout: 30000
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 600000
      pool-name: DatebookHikariCP
      max-lifetime: 28740000
      connection-test-query: SELECT 1
    url: jdbc:mysql://localhost:3306/netty_webchat?characterEncoding=utf-8
    username: root
    password: root



